[tool.poetry]
packages = [
    { include = "spikeannotator" }
]
name="spikeannotator"
version = "0.1.2"
description = ""
authors = ["Aidan Nickerson"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
mistune = "^0.8.4"
neo = "0.10.0"
numpy = "^1.20.2"
pandas = "^1.2.4"
plotly = "^5"
seaborn = "^0.11.1"
tqdm = "^4.61.2"
nixio = "^1.5.2"
h5py = "^3.6.0"
scipy = "^1.8.0"
PySide6 = "^6.2.3"
numba = "^0.55.2"
matplotlib = "^3.5.2"
PyWavelets = "^1.3.0"


[tool.poetry.dev-dependencies]
black = {version = "^21.7b0", allow-prereleases = true}
pyinstaller = "^4.10"
pyinstaller-hooks-contrib = "^2022.3"
ipython = "^8.4.0"

[tool.poetry.scripts]
spikeverify = "spikeannotator.mng_visualisation:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
